mysql_url: http://dev.mysql.com/get/Downloads/MySQL-5.6

mysql_ver: "5.6.27-1"

mysql_items:
  - rpm: MySQL-client-{{ mysql_ver }}.el6.x86_64.rpm
  - rpm: MySQL-shared-compat-{{ mysql_ver }}.el6.x86_64.rpm
  - rpm: MySQL-shared-{{ mysql_ver }}.el6.x86_64.rpm
  - rpm: MySQL-devel-{{ mysql_ver }}.el6.x86_64.rpm
  - rpm: MySQL-server-{{ mysql_ver }}.el6.x86_64.rpm

db_name: iroha

user_name: iroha

user_pass: iroha

